//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Utils.Localization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.Utils.Localization.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tümü.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tüm Bloglar.
        /// </summary>
        public static string AllBlogs {
            get {
                return ResourceManager.GetString("AllBlogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tüm Hakları Saklıdır.
        /// </summary>
        public static string AllRightsReserved {
            get {
                return ResourceManager.GetString("AllRightsReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog Listesi.
        /// </summary>
        public static string BlogList {
            get {
                return ResourceManager.GetString("BlogList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloglar.
        /// </summary>
        public static string Blogs {
            get {
                return ResourceManager.GetString("Blogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İLETİŞİM FORMU.
        /// </summary>
        public static string ContactForm {
            get {
                return ResourceManager.GetString("ContactForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstediğiniz zaman bize ulaşabilirsiniz..
        /// </summary>
        public static string ContactFormDescription {
            get {
                return ResourceManager.GetString("ContactFormDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detay.
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E Posta.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuma.
        /// </summary>
        public static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ana sayfa.
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesaj.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesajınız Başarıyla Gönderildi Teşekkürler!.
        /// </summary>
        public static string MessageSentSuccessDesc {
            get {
                return ResourceManager.GetString("MessageSentSuccessDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pazartesi.
        /// </summary>
        public static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daha Fazla.
        /// </summary>
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İsim Soyisim.
        /// </summary>
        public static string NameSurname {
            get {
                return ResourceManager.GetString("NameSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herhangi bir içerik bulunmamaktadır..
        /// </summary>
        public static string NoContentAvailableMessage {
            get {
                return ResourceManager.GetString("NoContentAvailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E Posta Adreslerimiz.
        /// </summary>
        public static string OurEmailAddresses {
            get {
                return ResourceManager.GetString("OurEmailAddresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon Numaralarımız.
        /// </summary>
        public static string OurPhoneNumbers {
            get {
                return ResourceManager.GetString("OurPhoneNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referanslarımız.
        /// </summary>
        public static string OurReferences {
            get {
                return ResourceManager.GetString("OurReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sosyal Medya Bağlantılarımız.
        /// </summary>
        public static string OurSocialMediaLinks {
            get {
                return ResourceManager.GetString("OurSocialMediaLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çözümlerimiz.
        /// </summary>
        public static string OurSolutions {
            get {
                return ResourceManager.GetString("OurSolutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çalışma Saatlerimiz.
        /// </summary>
        public static string OurWorkingHours {
            get {
                return ResourceManager.GetString("OurWorkingHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sayfalar.
        /// </summary>
        public static string Pages {
            get {
                return ResourceManager.GetString("Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon Numarası.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Detay.
        /// </summary>
        public static string ProductDetails {
            get {
                return ResourceManager.GetString("ProductDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürünler.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projeler.
        /// </summary>
        public static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oku.
        /// </summary>
        public static string Read {
            get {
                return ResourceManager.GetString("Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncel Blog Yazıları.
        /// </summary>
        public static string RecentBlogPosts {
            get {
                return ResourceManager.GetString("RecentBlogPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konu.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formu Gönder.
        /// </summary>
        public static string SubmitForm {
            get {
                return ResourceManager.GetString("SubmitForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teknik Destek.
        /// </summary>
        public static string TechnicalSupport {
            get {
                return ResourceManager.GetString("TechnicalSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E Posta Adresiniz.
        /// </summary>
        public static string YourEmailAddress {
            get {
                return ResourceManager.GetString("YourEmailAddress", resourceCulture);
            }
        }
    }
}
